#!/bin/sh

case "$1" in 
	start)
		echo "Starting aesdsocket server"
		start-stop-daemon -S -n logging -a /bin/logging -- -d
		;;
	stop)
		echo "Stoping aesdsocket server"
		start-stop-daemon -K -n logging
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0
