#!/bin/sh

function module_load
{
	#!/bin/sh
	module=aesdchar
	device=aesdchar
	mode="664"
	cd `dirname $0`
	set -e
	# Group: since distributions do it differently, look for wheel or use staff
	if grep -q '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	modprobe $module.ko $* || exit 1
	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
	rm -f /dev/${device}[0-2]


	mknod /dev/${device}0 c $major 0
	mknod /dev/${device}1 c $major 1
	mknod /dev/${device}2 c $major 2

	chgrp $group /dev/${device}[0-2]
	chmod $mode  /dev/${device}[0-2]
}

function module_unload
{
	#!/bin/sh
	module=aesdchar
	device=aesdchar
	cd `dirname $0`
	# invoke rmmod with all arguments we got
	rmmod $module || exit 1

	# Remove stale nodes

	rm -f /dev/${device}[0-2]
}

case "$1" in
	start)
		echo "Installing Modules"
		module_load aesdchar
		;;
	stop)
		echo "Removing modules"
		module_unload aesdchar
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0

