#!/bin/sh

case "$1" in 
	start)
		echo "Starting socket server daemon"
		start-stop-daemon -S -n server_socket -a /bin/server_socket -- -d
		;;
	stop)
		echo "Stoping socket server daemon"
		start-stop-daemon -K -n server_socket
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0
